version: '3.6'
services:
    web:
        build: .
        ports:
            - "5000:5000"
        environment:
            MYSQL_HOST: "sql.dg.io"
        links:
            - mariadb:sql.dg.io
    mariadb:
        image: mariadb:latest
        restart: always
        ports:
            - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: "hayDK0j!MYh15Do0"
        volumes:
            - ./db/production:/var/lib/mysql
        user: 1000:1000
